# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "@SyliusPriceHistoryPlugin/config/fixtures/*" }

parameters:
    sylius_price_history_api_resources_path: '%kernel.project_dir%/vendor/sylius/price-history-plugin/config/api_resources/'

api_platform:
    mapping:
        paths:
            - '%sylius_price_history_api_resources_path%'
