name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, MySQL ${{ matrix.mysql }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
                symfony: ["^5.4", "^6.0"]
                sylius: ["~1.11.14", "~1.12.4"]
                node: ["18.x"]
                mysql: ["5.7", "8.0"]

                exclude:
                    -
                        symfony: "^6.0"
                        sylius: "~1.11.14"

        env:
            APP_ENV: test
            DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?serverVersion=${{ matrix.mysql }}"
            application_dir: "tests/Application"

        steps:
            -
                uses: actions/checkout@v3

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl
                    tools: flex,symfony
                    coverage: none

            -
                name: Build application
                uses: jakubtobiasz/SyliusBuildTestAppAction@v2.0
                with:
                    e2e: "yes"
                    e2e_js: "yes"
                    database: "mysql"
                    database_version: ${{ matrix.mysql }}
                    php_version: ${{ matrix.php }}
                    symfony_version: ${{ matrix.symfony }}
                    sylius_version: ${{ matrix.sylius }}
                    node_version: ${{ matrix.node }}
                env:
                    application_dir: ${{ env.application_dir }}

            -
                name: Run ECS
                run: vendor/bin/ecs check

            -
                name: Run Arkitect
                run: vendor/bin/phparkitect check

            -
                name: Run PHPStan
                run: vendor/bin/phpstan analyse

            -
                name: Run Psalm
                run: vendor/bin/psalm

            -
                name: Run PHPSpec
                run: vendor/bin/phpspec run --ansi -f progress --no-interaction

            -
                name: Run PHPUnit
                run: vendor/bin/phpunit --colors=always

            -
                name: Run Behat
                run: vendor/bin/behat --format=progress --colors --strict -vvv --no-interaction --tags="~@todo"

            -
                name: Upload Behat logs
                uses: actions/upload-artifact@v2
                if: failure()
                with:
                    name: Behat logs
                    path: etc/build/
                    if-no-files-found: ignore

    tests-pgsql:
        runs-on: ubuntu-latest

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, PostgreSQL ${{ matrix.pgsql }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
                symfony: ["^5.4", "^6.0"]
                sylius: ["~1.11.14", "~1.12.4"]
                node: ["18.x"]
                pgsql: ["13.9", "14.6"]

                exclude:
                    -
                        symfony: "^6.0"
                        sylius: "~1.11.14"

        env:
            APP_ENV: test
            DATABASE_URL: "pgsql://root:root@127.0.0.1/sylius?serverVersion=${{ matrix.pgsql }}"
            application_dir: "tests/Application"

        steps:
            -
                uses: actions/checkout@v3

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl
                    tools: flex,symfony
                    coverage: none

            -
                name: Build application
                uses: jakubtobiasz/SyliusBuildTestAppAction@v2.0
                with:
                    e2e: "yes"
                    e2e_js: "yes"
                    database: "postgresql"
                    database_version: ${{ matrix.mysql }}
                    php_version: ${{ matrix.php }}
                    symfony_version: ${{ matrix.symfony }}
                    sylius_version: ${{ matrix.sylius }}
                    node_version: ${{ matrix.node }}

            -
                name: Run ECS
                run: vendor/bin/ecs check

            -
                name: Run Arkitect
                run: vendor/bin/phparkitect check

            -
                name: Run PHPStan
                run: vendor/bin/phpstan analyse

            -
                name: Run Psalm
                run: vendor/bin/psalm

            -
                name: Run PHPSpec
                run: vendor/bin/phpspec run --ansi -f progress --no-interaction

            -
                name: Run PHPUnit
                run: vendor/bin/phpunit --colors=always

            -
                name: Run Behat
                run: vendor/bin/behat --format=progress --colors --strict -vvv --no-interaction --tags="~@todo"

            -
                name: Upload Behat logs
                uses: actions/upload-artifact@v2
                if: failure()
                with:
                    name: Behat logs
                    path: etc/build/
                    if-no-files-found: ignore
